kind: Deployment
apiVersion: apps/v1
metadata:
  name: counter-database
  labels:
    app: counter-app
    app.kubernetes.io/part-of: counter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-database
      image: registry.redhat.io/rhel8/postgresql-15:latest
      imagePullPolicy: Always
      env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: counter-database
              key: database-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: counter-database
              key: database-password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: counter-database
              key: database-name
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        volumeMounts: 
          - name: counter-database-data
          mountPath: /var/lib/pgsql/data
        volumes: 
        - name: counter-database-data
          persistentVolumeClaim:
            claimName: counter-database-pvc