apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-backend
  labels:
    app: counter-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-backend
  template:
    metadata:
      labels:
        app: counter-backend
    spec:
      containers:
      - name: counter-backend
        image: counter-backend:v1  
        imagePullPolicy: Always
        env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-user
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-password
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: counter-database
                key: database-name
        ports:
        - containerPort: 3000 
