kind: Secret 
apiVersion: v1
metadata:
  name: counter-database
  Labels:
    app: counter-app
    app.kybernetes.io/part-of: counter-app
data:
  database-host: database-host
  database-name: database-name
  database-password: ZGF0YWJhc2UtcGFzc3dvcmQK
  database-user: ZGF0YWJhc2UtdXNlcgo=
type: Opaque
---
kind: Secret 
apiVersion: v1
metadata:
  name: counter-pgadmin
  labels:
    app: counter-app
    app.kubernetes.io/part-of: counter-app
data:
  PGADMIN DEFAULT EMAIL: 
  PGADMIN DEFAULT PASSIORD: 
type: Opaque